// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-aIA5JHiLOmd80N01TAMd3yKptH8Iek8',
    appId: '1:520842845240:web:91884bf77e2de8f34bdacd',
    messagingSenderId: '520842845240',
    projectId: 'workoutplanner-fd17e',
    authDomain: 'workoutplanner-fd17e.firebaseapp.com',
    storageBucket: 'workoutplanner-fd17e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOdIIq7ned0a7UCnDKV5Yt_JcDdnkxIT0',
    appId: '1:520842845240:android:d627d52f0fd822624bdacd',
    messagingSenderId: '520842845240',
    projectId: 'workoutplanner-fd17e',
    storageBucket: 'workoutplanner-fd17e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-aIA5JHiLOmd80N01TAMd3yKptH8Iek8',
    appId: '1:520842845240:web:393e8b70154f51a04bdacd',
    messagingSenderId: '520842845240',
    projectId: 'workoutplanner-fd17e',
    authDomain: 'workoutplanner-fd17e.firebaseapp.com',
    storageBucket: 'workoutplanner-fd17e.firebasestorage.app',
  );
}
